export const units = [
  //grail duo cheerleader binary healer refresher rearmed resplendent altHell
//{id: '', name: '', epithet: '', baseOrNot: '', special: '', games: [''], gameplayRole: '', weaponType: '', weaponColor: '', damageType: '', range: '', moveType: '', gender: '', image: 'pictures/.png'},



  //cormag
  //

  {id: 'alcrystBaseRearmed', name: 'Alcryst', epithet: 'Tender Archer', baseOrNot: 'base', special: 'rearmed', games: ['engage'], gameplayRole: 'pc', weaponType: 'bow', weaponColor: 'colorless', damageType: 'physical', range: '2', moveType: 'infantry', gender: 'm', image: 'pictures/alcrystBaseRearmed.png'},
  {id: 'arturSpecialWinter', name: 'Artur', epithet: 'Silver Saint', baseOrNot: 'special', special: 'winter', games: ['fe8'], gameplayRole: 'pc', weaponType: 'anima', weaponColor: 'green', damageType: 'magic', range: '2', moveType: 'armored', gender: 'm', image: 'pictures/arturSpecialWinter.png', altHell: true},
  {id: 'eliwoodBase', name: 'Eliwood', epithet: 'Knight of Lycia', baseOrNot: 'base', special: 'none', games: ['fe7'], gameplayRole: 'protagonist', weaponType: 'sword', weaponColor: 'red', damageType: 'physical', range: '1', moveType: 'cavalry', gender: 'm', image: 'pictures/eliwoodBase.png', resplendent: 'askr'},
  {id: 'knollBase', name: 'Knoll', epithet: 'Darkness Watcher', baseOrNot: 'base', special: 'none', games: ['fe8'], gameplayRole: 'pc', weaponType: 'dark', weaponColor: 'red', damageType: 'magic', range: '2', moveType: 'infantry', gender: 'm', image: 'pictures/knollBase.png'},
  {id: 'limstellaBase', name: 'Lismtella', epithet: 'Living Construct', baseOrNot: 'base', special: 'none', games: ['fe7'], gameplayRole: 'npc', weaponType: 'anima', weaponColor: 'green', damageType: 'magic', range: '2', moveType: 'infantry', gender: '', image: 'pictures/limstellaBase.png', grails: 'ghb'},
  {id: 'lucinaBase', name: 'Lucina', epithet: 'Future Witness', baseOrNot: 'base', special: 'none', games: ['fe13'], gameplayRole: 'pc', weaponType: 'sword', weaponColor: 'red', damageType: 'physical', range: '1', moveType: 'infantry', gender: 'f', image: 'pictures/lucinaBase.png', resplendent: 'ljosalfheimr'},
  {id: 'luciusBase', name: 'Lucius', epithet: 'The Light', baseOrNot: 'base', special: 'none', image: 'pictures/luciusBase.png', games: ['fe7'], gameplayRole: 'pc', weaponType: 'staff', weaponColor: 'colorless', damageType: 'magic', range: '2', moveType: 'infantry', gender: 'm', healer: true, resplendent: 'muspell'},
  {id: 'naesalaBase', name: 'Naesala', epithet: "Sky's Shadow", baseOrNot: 'base', special: 'none', games: ['FE10'], gameplayRole: 'pc', weaponType: 'beast', weaponColor: 'blue', damageType: 'physical', range: '1', moveType: 'flying', gender: 'm', image: 'pictures/naesalaBase.png', grails: 'ghb'},
  {id: 'naesalaSpecialPirate', name: 'Naesala', epithet: "Sea's Shadow", baseOrNot: 'special', special: 'pirate', games: ['fe10'], gameplayRole: 'pc', weaponType: 'beast', weaponColor: 'red', damageType: 'physical', range: '1', moveType: 'flying', gender: 'ma', image: 'pictures/naesalaSpecialPirate.png'},
  {id: 'natashaBase', name: 'Natasha', epithet: 'Sacred Healer', baseOrNot: 'base', special: 'none', games: ['fe8'], gameplayRole: 'pc', weaponType: 'staff', weaponColor: 'colorless', damageType: 'magic', range: '2', moveType: 'infantry', gender: 'f', image: 'pictures/natashaBase.png', healer: true},  {id: 'ninianBase', name: 'Ninian', epithet: 'Oracle of Destiny', baseOrNot: 'base', special: 'none', games: ['fe7'], gameplayRole: 'pc', weaponType: 'dragon', weaponColor: 'blue', damageType: 'physical', range: '1', moveType: 'infantry', gender: 'f', image: 'pictures/ninianBase.png', refresher: true, resplendent: 'nifl', resplendentImage: 'pictures/ninianBaseResplendent.png'},
  {id: 'ninianFallen', name: 'Ninian', epithet: 'Frozen Heart', baseOrNot: 'fallen', special: 'none', games: ['fe7'], gameplayRole: 'pc', weaponType: 'dragon', weaponColor: 'blue', damageType: 'physical', range: '1', moveType: 'infantry', gender: 'f', image: 'pictures/ninianFallen.png', refresher: true},
  {id: 'ninianLegendary', name: 'Ninian', epithet: 'Ice-Dragon Oracle', baseOrNot: 'legendary', special: 'none', games: ['fe7'], gameplayRole: 'pc', weaponType: 'dragon', weaponColor: 'green', damageType: 'physical', range: '1', moveType: 'cavalry', gender: 'f', image: 'pictures/ninianLegendary.png', refresher: true},
  {id: 'ninianSpecialWedding', name: 'Ninian', epithet: 'Bright-Eyed Bride', baseOrNot: 'special', special: 'wedding', games: ['fe7'], gameplayRole: 'pc', weaponType: 'light', weaponColor: 'blue', damageType: 'magic', range: '2', moveType: 'flying', gender: 'f', image: 'pictures/ninianSpecialWedding.png', refresher: true},
  {id: 'reysonBase', name: 'Reyson', epithet: 'White Prince', baseOrNot: 'base', special: 'none', games: ['fe10'], gameplayRole: 'pc', weaponType: 'beast', weaponColor: 'green', damageType: 'physical', range: '1', moveType: 'flying', gender: 'm', image: 'pictures/reysonBase.png', refresher: true},
  {id: 'rhysSpecialSummer', name: 'Rhys', epithet: 'Gentle Basker', baseOrNot: 'special', special: 'summer', games: ['fe10'], gameplayRole: 'pc', weaponType: 'staff', weaponColor: 'colorless', damageType: 'magic', range: '2', moveType: 'infantry', gender: 'm', image: 'pictures/rhysSpecialSummer.png', healer: true, altHell: true},
  {id: 'shigureBase', name: 'Shigure', epithet: 'Uplifting Artist', baseOrNot: 'base', special: 'none', games: ['fe14'], gameplayRole: 'pc', weaponType: 'lance', weaponColor: 'blue', damageType: 'physical', range: '1', moveType: 'flying', gender: 'm', image: 'pictures/shigureBase.png', resplendent: 'nifl'},
  {id: 'sorenFE9Base', name: 'Soren', epithet: 'Shrewd Strategist', baseOrNot: 'base', special: 'none', games: ['fe9'], gameplayRole: 'pc', weaponType: 'anima', weaponColor: 'green', damageType: 'magic', range: '2', moveType: 'infantry', gender: 'm', image: 'pictures/sorenFE9Base.png'},
  {id: 'sorenFE10Brave', name: 'Soren', epithet: 'Radiant Confidant', baseOrNot: 'brave', special: 'none', games: ['fe10'], gameplayRole: 'pc', weaponType: 'anima', weaponColor: 'green', damageType: 'magic', range: '2', moveType: 'infantry', gender: 'm', image: 'pictures/sorenFE10Brave.png', },
  //{id: '', name: '', epithet: '', baseOrNot: '', special: '', games: [''], gameplayRole: '', weaponType: '', weaponColor: '', damageType: '', range: '', moveType: '', gender: '', image: '.png'},
  //grail duo cheerleader binary healer refresher rearmed resplendent altHell
  //maybe add option to use thumbnails instead as a toggle
];